export const guests = {
1:["Alys Hernández ","Estimada",2,0],
2:["Valerin Domínguez ","Estimada",2,0],
3:["Santiago Velázquez ","Estimado",2,0],
4:["Sebastian Rúa ","Estimado",2,0],
5:["Kyara amaya ","Estimada",2,0],
6:["Jelitza Laborde ","Estimada",2,0],
7:["Rodolfo Sevilla ","Estimado",2,0],
8:["Heidy Martínez ","Estimada",2,0],
9:["Maylin Gutiérrez ","Estimada",2,0],
10:["Taliana Velázquez ","Estimada",2,0],
11:["Tío Adith ","Querido",4,0],
12:["Tío pellito ","Querido",4,0],
13:["Nubia ","Querida",4,0],
14:["Abuelo Toño ","Querido",3,0],
15:["Tía yuli ","Querida",2,0],
16:["Mami Astrid ","Querida",2,0],
17:["Tío Jimmy ","Querido",2,0],
18:["Clari Trujillo ","Querida",2,0],
19:["Flia. Figueroa ","Estimada",2,1],
20:["Yaneth Ramos ","Estimada",3,0],
21:["Silvana y César ","Estimados",2,1],
22:["Flia. Brochero Conrado ","Estimada",2,1],
23:["Flia. Moncada Miranda ","Estimada",2,1],
24:["Flia. Suárez Moncada ","Estimada",2,1],
25:["Flia. Moncada López ","Estimada",2,1],
26:["Flia. Orozco Moncada ","Estimada",4,1],
27:["Flia. Miranda Páez ","Estimada",2,1],
28:["Flia. Moncada Camargo ","Estimada",2,1],
29:["Flia. Moncada Barrios ","Estimada",2,1],
30:["Flia. Gutiérrez Acosta ","Estimada",2,1],
31:["Flia. Reyes ","Estimada",2,1],
32:["Flia. Orozco Paredes ","Estimada",2,1],
33:["Andrés Carrillo ","Estimado",2,0],
34:["Yennis Orozco ","Estimada",2,0],
35:["Flia. Conrado Rosano ","Estimada",2,1],
36:["Flia. Miranda castaño ","Estimada",2,1],
}

